In [1]:
from App import *

In [2]:
wsn = WSN(100, 9)
wsn.nodes = np.array([[64.86120825, 91.9678023 ],
            [34.051292  , 78.60951157],
            [39.23821726, 79.30016241],
            [ 2.89299521, 16.93997542],
            [66.56985748, 68.30029752],
            [77.38586504, 25.22644453],
            [ 8.18606883, 89.02124324],
            [96.13369847, 45.94076804],
            [87.70729065, 91.99485646]])
wsn.D = 200
wsn.reset_anchors(8)


In [19]:
def get_TDOA_H_and_b(self, results, *args, **kwargs):
    r1, t10, no1, *_ = results[0]

    # No transpose, because "rn - r1" are being inserted as rows
    H = np.array([r1 - rn for n, (rn, *_) in enumerate(results) if n != 0]) * 2
    H = np.concatenate((H, np.transpose([[-self.c * (tn0 - t10) * 2 for n, (rn, tn0, *_) in enumerate(results) if n != 0]])), 1)
    print(H)
    norm_r1_2 = np.dot(r1, r1)
    t10_2 = t10 ** 2
    tdoa = [tn0 - t10 for n, (rn, tn0, *_) in enumerate(results) if n != 0]
    print(tdoa)
    b = np.array([
        # [np.dot(rn, rn) - norm_r1_2 - self.c ** 2 * ((tn0 - t10) ** 2 + 2 * t10 * (tn0 - t10))]
        [(self.c * (tn0 - t10)) **2 + norm_r1_2 - np.dot(rn, rn)]
        for n, (rn, tn0, no, *_) in enumerate(results) if n != 0
    ])
    return H, b

In [20]:
results = wsn.transmit(8, wsn.nodes[8])
H, b = get_TDOA_H_and_b(wsn, results)


[[  61.6198325    26.71658146  -64.90859247]
 [  51.24598198   25.33527978  -54.51571367]
 [ 123.93642608  150.05565376 -180.81784602]
 [  -3.41729846   47.33500956  -17.81286452]
 [ -25.04931358  133.48271554  -89.43074952]
 [ 113.35027884    5.89311812 -113.46140313]
 [ -62.54498044   92.05406852  -47.94504808]]
[1.0818098745308465e-07, 9.085952279156315e-08, 3.0136307670155407e-07, 2.9688107526930526e-08, 1.490512492050805e-07, 1.891023385434686e-07, 7.990841346735943e-08]


In [21]:
print(H)
print(b)
print(np.matmul(np.linalg.pinv(H), b))
print(wsn.nodes[8])
print(wsn.known_nodes)

[[  61.6198325    26.71658146  -64.90859247]
 [  51.24598198   25.33527978  -54.51571367]
 [ 123.93642608  150.05565376 -180.81784602]
 [  -3.41729846   47.33500956  -17.81286452]
 [ -25.04931358  133.48271554  -89.43074952]
 [ 113.35027884    5.89311812 -113.46140313]
 [ -62.54498044   92.05406852  -47.94504808]]
[[ 6379.38854357]
 [ 5579.89030292]
 [20543.49416694]
 [ 3647.90096488]
 [ 8039.57212399]
 [ 7891.63202449]
 [ 1887.49275477]]
[[87.70729065]
 [91.99485646]
 [22.84609842]]
[87.70729065 91.99485646]
{0, 1, 2, 3, 4, 5, 6, 7}


In [6]:
print(wsn.nodes[2])
print(wsn.nodes[8])
print(dist(wsn.nodes[8], wsn.nodes[2]))
print(len(results))
print([dist(n, wsn.nodes[8]) for n in wsn.nodes])


[39.23821726 79.30016241]
[87.70729065 91.99485646]
50.10395525613035
8
[22.846098418661402, 55.300394654586796, 50.10395525613035, 113.25502142912762, 31.75253067674056, 67.56147318018554, 79.57679998170198, 46.81862245886923, 0.0]
