In [1]:
from App import *

In [2]:
wsn = WSN(100, 9)
wsn.nodes = np.array([[64.86120825, 91.9678023 ],
            [34.051292  , 78.60951157],
            [39.23821726, 79.30016241],
            [ 2.89299521, 16.93997542],
            [66.56985748, 68.30029752],
            [77.38586504, 25.22644453],
            [ 8.18606883, 89.02124324],
            [96.13369847, 45.94076804],
            [87.70729065, 91.99485646]])
wsn.D = 200
wsn.reset_anchors(8)


In [32]:
def get_TDOA_H_and_b(self, results, *args, **kwargs):
    r1, t10, no1, *_ = results[0]

    # No transpose, because "rn - r1" are being inserted as rows
    H = np.array([rn - r1 for n, (rn, *_) in enumerate(results) if n != 0])
    H = np.concatenate((H, np.transpose([[self.c * (tn0 - t10) for n, (rn, tn0, *_) in enumerate(results) if n != 0]])), 1)
    print(H)
    norm_r1_2 = np.dot(r1, r1)
    t10_2 = t10 ** 2
    tdoa = [tn0 - t10 for n, (rn, tn0, *_) in enumerate(results) if n != 0]
    print(tdoa)
    b = np.array([
        [np.dot(rn, rn) - norm_r1_2 - (self.c * (tn0 - t10)) ** 2]
        for n, (rn, tn0, no, *_) in enumerate(results) if n != 0
    ]) * 0.5
    return H, b

In [33]:
results = wsn.transmit(8, wsn.nodes[8])
H, b = get_TDOA_H_and_b(wsn, results)


[[-30.80991625 -13.35829073  32.45429624]
 [-25.62299099 -12.66763989  27.25785684]
 [-61.96821304 -75.02782688  90.40892301]
 [  1.70864923 -23.66750478   8.90643226]
 [ 12.52465679 -66.74135777  44.71537476]
 [-56.67513942  -2.94655906  56.73070156]
 [ 31.27249022 -46.02703426  23.97252404]]
[1.0818098745308465e-07, 9.085952279156315e-08, 3.0136307670155407e-07, 2.9688107526930526e-08, 1.490512492050805e-07, 1.891023385434686e-07, 7.990841346735943e-08]


In [34]:
print(H)
print(b)
print(np.matmul(np.linalg.pinv(H), b))
print(wsn.nodes[8])
print(wsn.known_nodes)

[[-30.80991625 -13.35829073  32.45429624]
 [-25.62299099 -12.66763989  27.25785684]
 [-61.96821304 -75.02782688  90.40892301]
 [  1.70864923 -23.66750478   8.90643226]
 [ 12.52465679 -66.74135777  44.71537476]
 [-56.67513942  -2.94655906  56.73070156]
 [ 31.27249022 -46.02703426  23.97252404]]
[[ -3189.69427178]
 [ -2789.94515146]
 [-10271.74708347]
 [ -1823.95048244]
 [ -4019.786062  ]
 [ -3945.81601225]
 [  -943.74637739]]
[[87.70729065]
 [91.99485646]
 [22.84609842]]
[87.70729065 91.99485646]
{0, 1, 2, 3, 4, 5, 6, 7}


In [6]:
print(wsn.nodes[2])
print(wsn.nodes[8])
print(dist(wsn.nodes[8], wsn.nodes[2]))
print(len(results))
print([dist(n, wsn.nodes[8]) for n in wsn.nodes])


[39.23821726 79.30016241]
[87.70729065 91.99485646]
50.10395525613035
8
[22.846098418661402, 55.300394654586796, 50.10395525613035, 113.25502142912762, 31.75253067674056, 67.56147318018554, 79.57679998170198, 46.81862245886923, 0.0]
